pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Maven Build') {
            steps {
                dir('demo'){
                sh 'mvn clean package -DskipTests'
            }              
            }
        }

        stage('Maven Test') {
            steps {
                dir('demo'){
                    sh 'mvn test'
                }                
            }
        }

        stage('Docker Build'){
            steps {
                dir('demo'){
                    sh 'docker build -t demo:{BUILD_NUMBER} .'
                }
            }
        }
    }

    post {
        success {
            echo 'Maven build and test completed successfully'
        }

        failure {
            echo 'Maven build or test failed'
        }
    }
}