pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Maven Build') {
            steps {
                dir('demo'){
                sh 'mvn clean package -DskipTests'
            }              
            }
        }

        stage('Maven Test') {
            steps {
                dir('demo'){
                    sh 'mvn test'
                }                
            }
        }

        stage('Docker Build'){
            steps {
                dir('demo'){
                    sh 'docker build -t demo:${BUILD_NUMBER} .'
                }
            }
        }
        stage('Show Build Number'){
            steps{
                echo "BUILD_NUMBER = ${BUILD_NUMBER}"
            }
        }
        stage('AWS Test'){
            steps{
                withCredentials([
                    string(
                        credentialsId: 'aws-access-key',
                        variable: 'AWS_ACCESS_KEY_ID'
                        )
                        string(
                            credentialsId: 'aws-sceret-key',
                            variable: 'AWS_SCERET_ACCESS_KEY'
                        )
                ]){
                    sh '''
                    aws sts get caller-identity
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Maven build and test completed successfully'
        }

        failure {
            echo 'Maven build or test failed'
        }
    }
}