pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Maven Build') {
            steps {
                dir('demo') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Maven Test') {
            steps {
                dir('demo') {
                    sh 'mvn test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('demo') {
                    sh '''
            docker tag demo:${BUILD_NUMBER} \
           979939293482.dkr.ecr.ap-south-1.amazonaws.com/demo:${BUILD_NUMBER}
        '''
                    }
                }
            }

            stage('Push to ECR'){
                steps{
                    sh '''
                    docker push \
                    979939293482.dkr.ecr.ap-south-1.amazonaws.com/demo:${BUILD_NUMBER}
                    '''
                }
            }
             
    

        stage('Show Build Number') {
            steps {
                echo "BUILD_NUMBER = ${BUILD_NUMBER}"
            }
        }

        stage('AWS Test') {
            steps {
                withCredentials([
                    string(
                        credentialsId: 'aws-access-key',
                        variable: 'AWS_ACCESS_KEY_ID'
                    ),
                    string(
                        credentialsId: 'aws-secret-key',
                        variable: 'AWS_SECRET_ACCESS_KEY'
                    )
                ]) {
                    sh '''
                        aws sts get-caller-identity
                    '''
                }
            }
        }
        stage ('ECR Login') {
            steps{
                withCredentials([
                    string(credentialsId:'aws-access-key',
                           variable:'AWS_ACCESS_KEY_ID'),
                    string(credentialsId:'aws_secret_key',
                            variable:'AWS_SECRET_ACCESS_KEY')
                ]) {
                    sh '''
                aws ecr get-login-password --region ap-south-1 | \
                docker login \
                --username AWS \
                --password-stdin 979939293482.dkr.ecr.ap-south-1.amazonaws.com
            '''
                }
            }
        }
    }

    post {
        success {
            echo 'Maven build and test completed successfully'
        }

        failure {
            echo 'Maven build or test failed'
        }
    }
}
