name: Banking CI/CD

on:
  push:
    branches:
      - cicd-feature

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4


      # 2. Setup Java
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven


      # 3. Build Spring Boot application
      - name: Build application
        run: |
          mvn clean package -DskipTests


      # 4. Configure AWS using GitHub OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}


      # 5. Login to Amazon ECR
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # 6. Build Docker image
      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} .


      # 7. Push Docker image to ECR
      - name: Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}


      # 8. Update ECS service
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster banking-cicd-cluster \
            --service banking-cicd-service \
            --force-new-deployment


      # 9. Wait for ECS deployment
      - name: Wait for ECS deployment
        run: |
          aws ecs wait services-stable \
            --cluster banking-cicd-cluster \
            --services banking-cicd-service


      # 10. Deployment successful
      - name: Deployment successful
        run: |
          echo "Deployment completed successfully!"
          echo "Docker image: ${{ github.sha }}"